
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security-test-db
    username: root
    password: Cqy19981202

mybatis:
  mapper-locations: classpath:/mapper/UserMapper.xml
server:
  port: 8900